name: Republish vllm-openai image

on:
  workflow_dispatch:
  schedule:
    # rebuild image every sunday
    - cron: "0 0 * * 0"

#permissions:
#  contents: read
#  packages: write
#  id-token: write
#  pull-requests: write

jobs:
  republish-vllm-openai:
    name: Republish vllm-openai image
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Greenbone Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GREENBONE_REGISTRY }}
          username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push image to GHCR and Harbor
        run: |
          docker buildx imagetools create \
            --tag greenbone/vllm-openai:latest \
            --tag ${{ vars.GREENBONE_REGISTRY }}/openvas-ai/vllm-openai:latest \
            vllm/vllm-openai:latest
