name: Republish llama.cpp image

on:
  workflow_dispatch:
  schedule:
    # rebuild image every sunday
    - cron: "0 0 * * 0"

jobs:
  republish-vllm-openai:
    name: Republish llama.cpp image
    runs-on: self-hosted-generic

    steps:
      - name: Login to Greenbone Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GREENBONE_REGISTRY }}
          username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GREENBONE_BOT }}
          password: ${{ secrets.GREENBONE_BOT_PACKAGES_WRITE_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/greenbone/llama.cpp:server-cuda \
            ghcr.io/ggml-org/llama.cpp:server-cuda

      - name: Push image to Harbor
        run: |
          docker buildx imagetools create \
            --tag ${{ vars.GREENBONE_REGISTRY }}/openvas-ai/llama.cpp:server-cuda \
            ghcr.io/ggml-org/llama.cpp:server-cuda
